server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eric-anunciacao/microservice-repo
          search-paths: fornecedor, loja, transportador
          